runtime: nodejs16
service_account: jenkins-account@soa-karaoke.iam.gserviceaccount.com
service: client

handlers:
  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'